name: pull request comment
on:
  pull_request_target:                                     
    types: [edited]

jobs:
 job01:
   runs-on: [ubuntu-latest]
   steps:
    - name: Debug action
      uses: hmarr/debug-action@v2.0.0
