name: pull request comment
on:
  issue_comment:                                     
    types: [created]

jobs:
 job01:
   runs-on: [ubuntu-latest]
   steps:
    - name: Debug action
      uses: hmarr/debug-action@v2.0.0
